CFLAGS = -std=gnu11 -Wall -Werror -Wextra

.PHONY: all
all: task3_server task3_client

.PHONY: clean
clean:
	$(RM) task3_server task3_client

task3_server: task3_server.c

task3_client: task3_client.c

